using System.Text;

namespace Valhalla.Gen;

sealed class CodeWriter
{
    readonly StringBuilder m_Sb = new();
    int m_Indent;

    public CodeWriter Line(string text = "")
    {
        if (text.Length == 0) m_Sb.Append('\n');
        else m_Sb.Append('\t', m_Indent).Append(text).Append('\n');
        return this;
    }

    public CodeWriter Open(string text)
    {
        Line(text.Length == 0 ? "{" : text + " {");
        m_Indent++;
        return this;
    }

    public CodeWriter Close(string suffix = "")
    {
        m_Indent--;
        Line("}" + suffix);
        return this;
    }

    public override string ToString() => m_Sb.ToString();
}

sealed class ModuleEmitter
{
    const string Banner = "// Generated by Valhalla-Gen. Do not edit; changes are overwritten on the next build.";

    readonly ModuleConfig m_Module;
    readonly Inventory m_Inv;
    readonly List<TypeModel> m_Types;
    readonly List<EnumModel> m_Enums;
    readonly string m_Rtls;
    readonly string m_ThunkNs;

    public Dictionary<string, string> Files { get; } = new(StringComparer.OrdinalIgnoreCase);

    public ModuleEmitter(ModuleConfig module, Inventory inv)
    {
        m_Module = module;
        m_Inv = inv;
        m_Types = inv.Types.Where(t => inv.OwnerOf(t) == module).ToList();
        m_Enums = inv.Enums.Where(e => e.Module == module).ToList();
        m_Rtls = $"{module.Namespace}::ValhallaRTLS";
        m_ThunkNs = $"ValhallaThunks_{Model.Identifier(module.Namespace)}";
    }

    public void Emit()
    {
        EmitCtlsHeaders();
        EmitRegistryHeader();
        EmitUnity();
    }

    static string Hex(ulong v) => $"0x{v:x16}ULL";

    // offsetof on non-standard-layout types (anything with virtuals or bases) is conditionally-supported but works on every target compiler.
    static void PushOffsetofSuppression(CodeWriter w) => w
        .Line("#if defined(__clang__)").Line("#pragma clang diagnostic push").Line("#pragma clang diagnostic ignored \"-Winvalid-offsetof\"")
        .Line("#elif defined(__GNUC__)").Line("#pragma GCC diagnostic push").Line("#pragma GCC diagnostic ignored \"-Winvalid-offsetof\"")
        .Line("#endif");

    static void PopOffsetofSuppression(CodeWriter w) => w
        .Line("#if defined(__clang__)").Line("#pragma clang diagnostic pop")
        .Line("#elif defined(__GNUC__)").Line("#pragma GCC diagnostic pop")
        .Line("#endif");
    static string NsOpen(string[] ns) => ns.Length == 0 ? "" : "::" + string.Join("::", ns);

    string IncludePath(string header)
    {
        string rel = Path.GetRelativePath(m_Module.OutputPath, header).Replace('\\', '/');
        return $"#include \"{rel}\"";
    }

    static string Traits(string enumName, List<string> traits) =>
        traits.Count == 0 ? $"::Valhalla::{enumName}::None" : string.Join(" | ", traits.Select(t => $"::Valhalla::{enumName}::{t}"));

    void AddFile(string name, string content, string sourceFile, int line)
    {
        if (Files.ContainsKey(name))
        {
            Diag.Error(sourceFile, line, $"Two reflected declarations in module {m_Module.ModuleName} would both generate '{name}'; rename one.");
            return;
        }
        Files[name] = content;
    }

    void EmitCtlsHeaders()
    {
        foreach (var group in m_Types.GroupBy(t => t.Source))
        {
            var raw = group.Key;
            var w = new CodeWriter();
            w.Line(Banner).Line("#pragma once").Line("#include \"ValhallaCTLS.h\"").Line(IncludePath(raw.Header));
            foreach (string header in group.SelectMany(ReferencedHeaders).Distinct(StringComparer.OrdinalIgnoreCase).Where(h => h != raw.Header))
                w.Line(IncludePath(header));
            w.Line();
            PushOffsetofSuppression(w);
            w.Line();
            w.Open($"namespace Valhalla::CTLS{NsOpen(raw.Namespace)}");

            if (raw.IsTemplate)
            {
                w.Line($"template <{Lexer.Join(raw.TemplateParams!)}>");
                w.Line($"struct {raw.Name};");
                w.Line();
            }
            foreach (var type in group)
            {
                if (raw.IsTemplate) w.Line("template <>");
                EmitCtlsType(w, type, raw.IsTemplate ? $"struct {raw.Name}<{type.SpecializationArgsEmit}>" : $"struct {type.Name}");
                w.Line();
            }
            w.Close();
            w.Line();
            PopOffsetofSuppression(w);
            AddFile($"{raw.Name}.generated.h", w.ToString(), raw.Header, raw.Line);
        }

        foreach (var e in m_Enums)
        {
            var w = new CodeWriter();
            w.Line(Banner).Line("#pragma once").Line("#include \"ValhallaCTLS.h\"").Line(IncludePath(e.Source.Header)).Line();
            w.Open($"namespace Valhalla::CTLS{NsOpen(e.Namespace)}");
            EmitCtlsEnum(w, e);
            w.Close();
            AddFile($"{e.Name}.generated.h", w.ToString(), e.Source.Header, e.Source.Line);
        }
    }

    IEnumerable<string> ReferencedHeaders(TypeModel type)
    {
        IEnumerable<TypeRef> refs = type.Fields.Select(f => f.Type)
            .Concat(type.Methods.Concat(type.Operators).SelectMany(m => m.Params.Select(p => p.Type).Append(m.ReturnType)))
            .Concat(type.Constructors.SelectMany(c => c.Params.Select(p => p.Type)));
        foreach (var r in refs)
        {
            if (r.Type != null) yield return r.Type.Source.Header;
            if (r.Enum != null) yield return r.Enum.Source.Header;
        }
        if (type.Parent != null) yield return type.Parent.Source.Header;
    }

    void EmitCommonMeta(CodeWriter w, string objectType, ulong hash, string align, string name, MetaStrings meta)
    {
        w.Line($"static constexpr ::Valhalla::ObjectType kObjectType = ::Valhalla::ObjectType::{objectType};");
        w.Line($"static constexpr uint64_t kTypeHash = {Hex(hash)};");
        w.Line("static constexpr uint32_t kSize = static_cast<uint32_t>(sizeof(ValhallaSelf));");
        w.Line($"static constexpr uint32_t kAlign = {align};");
        w.Line($"static constexpr const char* kName = {Model.Literal(name)};");
        w.Line($"static constexpr const char* kDisplayName = {meta.DisplayName};");
        w.Line($"static constexpr const char* kCategory = {meta.Category};");
        w.Line($"static constexpr const char* kTooltip = {meta.Tooltip};");
    }

    void EmitCtlsType(CodeWriter w, TypeModel type, string head)
    {
        w.Open(head);
        w.Line($"using ValhallaSelf = {type.FullEmitName};");
        w.Line();
        string align = type.Align is int a ? $"{a}u" : "static_cast<uint32_t>(alignof(ValhallaSelf))";
        EmitCommonMeta(w, type.IsClass ? "Class" : "Struct", type.Hash, align, type.QualifiedName, type.Meta);
        w.Line($"static constexpr uint64_t kParentHash = {(type.Parent != null ? Hex(type.Parent.Hash) : "0ULL")};");
        w.Line();

        w.Open("struct Fields");
        foreach (var f in type.Fields)
        {
            w.Open($"struct {f.Name}");
            w.Line($"static constexpr const char* kName = {Model.Literal(f.Name)};");
            w.Line($"static constexpr uint32_t kOffset = {FieldOffset(type, f)};");
            w.Line($"static constexpr uint32_t kSize = static_cast<uint32_t>(sizeof(decltype(ValhallaSelf::{f.Name})));");
            w.Line($"static constexpr uint32_t kAlign = {FieldAlign(f, "ValhallaSelf")};");
            w.Line($"static constexpr ::Valhalla::Visibility kVisibility = ::Valhalla::Visibility::{f.Visibility};");
            w.Line($"static constexpr ::Valhalla::LangTraits kLangTraits = {Traits("LangTraits", f.LangTraits)};");
            w.Line($"static constexpr ::Valhalla::ReflectTraits kReflectTraits = {Traits("ReflectTraits", f.ReflectTraits)};");
            w.Line($"static constexpr ::Valhalla::ToolTraits kToolTraits = {Traits("ToolTraits", f.ToolTraits)};");
            w.Close(";");
        }
        w.Close(";");
        w.Line();

        w.Open("struct Methods");
        foreach (var m in type.Methods) EmitCtlsCallable(w, m, isOperator: false);
        w.Close(";");
        w.Line();

        w.Open("struct Operators");
        foreach (var m in type.Operators) EmitCtlsCallable(w, m, isOperator: true);
        w.Close(";");
        w.Line();

        w.Open("struct Constructors");
        foreach (var c in type.Constructors)
        {
            w.Open($"struct {c.Ident}");
            w.Line($"static constexpr ::Valhalla::ConstructorKind kKind = ::Valhalla::ConstructorKind::{c.Kind};");
            w.Line($"static constexpr ::Valhalla::Visibility kVisibility = ::Valhalla::Visibility::{c.Visibility};");
            switch (c.Kind)
            {
                case "Default":
                    w.Line("static ValhallaSelf* Invoke(void* p_Memory) { return ::new (p_Memory) ValhallaSelf(); }");
                    break;
                case "Copy":
                    w.Line("static ValhallaSelf* Invoke(void* p_Memory, const ValhallaSelf& r_Other) { return ::new (p_Memory) ValhallaSelf(r_Other); }");
                    break;
                case "Move":
                    w.Line("static ValhallaSelf* Invoke(void* p_Memory, ValhallaSelf&& u_Other) { return ::new (p_Memory) ValhallaSelf(std::move(u_Other)); }");
                    break;
                default:
                    w.Line($"static constexpr uint32_t kParamCount = {c.Params.Count};");
                    w.Line("template <typename... TArgs>");
                    w.Line("static ValhallaSelf* Invoke(void* p_Memory, TArgs&&... u_Args) { return ::new (p_Memory) ValhallaSelf(std::forward<TArgs>(u_Args)...); }");
                    break;
            }
            w.Close(";");
        }
        w.Close(";");
        w.Line();

        w.Open("struct Destructor");
        w.Line("static void Invoke(ValhallaSelf* p_Instance) { std::destroy_at(p_Instance); }");
        w.Close(";");
        w.Close(";");
    }

    static string FieldOffset(TypeModel type, FieldModel f) =>
        f.IsStatic ? "0u" : $"static_cast<uint32_t>(offsetof({type.FullEmitName}, {f.Name}))";

    static string FieldAlign(FieldModel f, string owner) =>
        f.Align is int a ? $"{a}u" : $"static_cast<uint32_t>(alignof(decltype({owner}::{f.Name})))";

    void EmitCtlsCallable(CodeWriter w, MethodModel m, bool isOperator)
    {
        w.Open($"struct {m.Ident}");
        w.Line($"static constexpr const char* kName = {Model.Literal(m.Name)};");
        w.Line($"static constexpr uint64_t kHash = {Hex(Fnv.Hash(m.Name))};");
        if (isOperator) w.Line($"static constexpr ::Valhalla::OperatorKind kOp = ::Valhalla::OperatorKind::{m.Operator};");
        w.Line($"static constexpr uint32_t kParamCount = {m.Params.Count};");
        w.Line($"static constexpr ::Valhalla::Visibility kVisibility = ::Valhalla::Visibility::{m.Visibility};");
        w.Line($"static constexpr ::Valhalla::LangTraits kLangTraits = {Traits("LangTraits", m.LangTraits)};");
        w.Line($"static constexpr ::Valhalla::ReflectTraits kReflectTraits = {Traits("ReflectTraits", m.ReflectTraits)};");
        w.Line($"static constexpr ::Valhalla::ToolTraits kToolTraits = {Traits("ToolTraits", m.ToolTraits)};");
        w.Line("template <typename... TArgs>");
        if (m.IsStatic)
        {
            w.Line($"static decltype(auto) Invoke(TArgs&&... u_Args) {{ return ValhallaSelf::{m.Name}(std::forward<TArgs>(u_Args)...); }}");
        }
        else
        {
            string self = m.IsConst ? "const ValhallaSelf*" : "ValhallaSelf*";
            w.Line($"static decltype(auto) Invoke({self} p_Instance, TArgs&&... u_Args) {{ return p_Instance->{m.Name}(std::forward<TArgs>(u_Args)...); }}");
        }
        w.Close(";");
    }

    void EmitCtlsEnum(CodeWriter w, EnumModel e)
    {
        w.Open($"struct {e.Name}");
        w.Line($"using ValhallaSelf = {e.FullEmitName};");
        w.Line();
        EmitCommonMeta(w, "Enum", e.Hash, "static_cast<uint32_t>(alignof(ValhallaSelf))", e.QualifiedName, e.Meta);
        w.Line($"static constexpr uint32_t kCount = {e.Values.Count};");
        w.Line();
        w.Open("struct Entry");
        w.Line("ValhallaSelf m_Value;");
        w.Line("int64_t m_IntValue;");
        w.Line("const char* m_Name;");
        w.Line("const char* m_DisplayName;");
        w.Close(";");
        w.Line();
        w.Open("static constexpr Entry kEntries[] =");
        foreach (var v in e.Values)
            w.Line($"{{ ValhallaSelf::{v.Name}, {EnumIntValue(v)}, {Model.Literal(v.Name)}, {v.DisplayName} }},");
        w.Close(";");
        w.Line();
        w.Open("static constexpr const char* ToString(ValhallaSelf v_Value)");
        w.Line("for (const Entry& entry : kEntries) if (entry.m_Value == v_Value) return entry.m_Name;");
        w.Line("return nullptr;");
        w.Close();
        w.Open("static constexpr const char* ToDisplayName(ValhallaSelf v_Value)");
        w.Line("for (const Entry& entry : kEntries) if (entry.m_Value == v_Value) return entry.m_DisplayName;");
        w.Line("return nullptr;");
        w.Close();
        w.Open("static constexpr bool FromString(std::string_view v_Name, ValhallaSelf& r_Out)");
        w.Line("for (const Entry& entry : kEntries) if (v_Name == entry.m_Name) { r_Out = entry.m_Value; return true; }");
        w.Line("return false;");
        w.Close();
        w.Open("static constexpr int64_t ToInt(ValhallaSelf v_Value)");
        w.Line("for (const Entry& entry : kEntries) if (entry.m_Value == v_Value) return entry.m_IntValue;");
        w.Line("return static_cast<int64_t>(v_Value);");
        w.Close();
        w.Open("static constexpr bool FromInt(int64_t v_Int, ValhallaSelf& r_Out)");
        w.Line("for (const Entry& entry : kEntries) if (entry.m_IntValue == v_Int) { r_Out = entry.m_Value; return true; }");
        w.Line("return false;");
        w.Close();
        w.Close(";");
    }

    static string EnumIntValue(EnumValueModel v) =>
        v.Override is long o ? $"{o}LL" : $"static_cast<int64_t>(ValhallaSelf::{v.Name})";

    string RegistryHeaderName => $"{m_Module.ModuleName}Registry.generated.h";

    void EmitRegistryHeader()
    {
        var w = new CodeWriter();
        w.Line(Banner).Line("#pragma once").Line("#include \"ValhallaRegistry.h\"").Line();
        w.Open($"namespace {m_Module.Namespace}");
        w.Line($"inline constexpr uint64_t kValhallaDllHash = {Hex(m_Module.DllHash)}; // fnv1a({Model.Literal(m_Module.DllIdentity)})");
        w.Line();
        w.Open("namespace ValhallaTypeHashes");
        foreach (var t in m_Types) w.Line($"inline constexpr uint64_t k{t.Ident} = {Hex(t.Hash)};");
        foreach (var e in m_Enums) w.Line($"inline constexpr uint64_t k{e.Ident} = {Hex(e.Hash)};");
        w.Close();
        w.Line();
        w.Open("inline const ::Valhalla::TypeDescriptor* GetReflectedType(uint64_t v_TypeHash)");
        w.Line("return ::Valhalla::GetType(kValhallaDllHash, v_TypeHash);");
        w.Close();
        w.Close();
        AddFile(RegistryHeaderName, w.ToString(), m_Module.BuildFile, 1);
    }

    string TypeRefExpr(TypeRef r) => r.Kind switch
    {
        TypeRefKind.Void => "nullptr",
        TypeRefKind.Primitive => $"&::Valhalla::kType_{r.Primitive}",
        TypeRefKind.Reflected when m_Inv.OwnerOf(r.Type!) == m_Module => $"&::{m_Rtls}::kType_{r.Type!.Ident}",
        TypeRefKind.Enum when r.Enum!.Module == m_Module => $"&::{m_Rtls}::kType_{r.Enum!.Ident}",
        // Cross-module descriptors live in another DLL's data segment and can't be constant-initialised from here.
        _ => "nullptr",
    };

    void WarnCrossModule(TypeRef r, string file, int line, string what)
    {
        if (r.Kind == TypeRefKind.Reflected && m_Inv.OwnerOf(r.Type!) != m_Module)
            Diag.Warning(file, line, $"{what} refers to '{r.Type!.QualifiedName}' from another module; its runtime descriptor pointer is left null (look it up by hash).");
        if (r.Kind == TypeRefKind.Enum && r.Enum!.Module != m_Module)
            Diag.Warning(file, line, $"{what} refers to '{r.Enum!.QualifiedName}' from another module; its runtime descriptor pointer is left null (look it up by hash).");
    }

    static string LangOf(TypeRef r) => r.IsConst ? "::Valhalla::LangTraits::Const" : "::Valhalla::LangTraits::None";

    static string ReflectOf(TypeRef r)
    {
        var list = new List<string>();
        if (r.IsPointer) list.Add("Pointer");
        if (r.IsReference) list.Add("Reference");
        return Traits("ReflectTraits", list);
    }

    string MethodSignature(TypeModel type, MethodModel m)
    {
        string ps = string.Join(", ", m.Params.Select(p => p.TypeText));
        string ret = m.ReturnText.Length == 0 ? "void" : m.ReturnText;
        return m.IsStatic ? $"{ret} (*)({ps})" : $"{ret} ({type.FullEmitName}::*)({ps}){(m.IsConst ? " const" : "")}";
    }

    void EmitUnity()
    {
        var w = new CodeWriter();
        w.Line(Banner).Line("#include \"ValhallaRTLS.h\"").Line($"#include \"{RegistryHeaderName}\"");

        var headers = m_Types.SelectMany(t => ReferencedHeaders(t).Prepend(t.Source.Header))
            .Concat(m_Enums.Select(e => e.Source.Header))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(h => h, StringComparer.OrdinalIgnoreCase);
        foreach (string h in headers) w.Line(IncludePath(h));
        w.Line();
        PushOffsetofSuppression(w);
        w.Line();

        w.Open($"namespace {m_Rtls}");
        foreach (var t in m_Types) w.Line($"extern const ::Valhalla::TypeDescriptor kType_{t.Ident};");
        foreach (var e in m_Enums) w.Line($"extern const ::Valhalla::TypeDescriptor kType_{e.Ident};");
        w.Close();
        w.Line();

        foreach (var t in m_Types) EmitThunks(w, t);
        foreach (var t in m_Types) EmitTypeDescriptors(w, t);
        foreach (var e in m_Enums) EmitEnumDescriptor(w, e);
        EmitModuleRegistry(w);

        AddFile($"{m_Module.ModuleName}.generated.cpp", w.ToString(), m_Module.BuildFile, 1);
    }

    // Thunks live in the reflected type's own namespace so unqualified parameter spellings resolve as in the header.
    void EmitThunks(CodeWriter w, TypeModel t)
    {
        bool hasNs = t.Namespace.Length > 0;
        if (hasNs) w.Open($"namespace {string.Join("::", t.Namespace)}");
        w.Open($"namespace {m_ThunkNs}");

        foreach (var m in t.Methods.Concat(t.Operators))
        {
            if (m.IsAbstract) continue;
            string sig = MethodSignature(t, m);
            string fn = $"static_cast<{sig}>(&{t.FullEmitName}::{m.Name})";
            w.Line($"constexpr ::Valhalla::ThunkFn kThunk_{t.Ident}_{m.Ident} = &::Valhalla::Detail::methodThunk<{fn}>;");
            if (m.ReflectTraits.Contains("Functor"))
                w.Line($"constexpr auto kFunctor_{t.Ident}_{m.Ident} = {fn};");
        }
        foreach (var c in t.Constructors)
        {
            string thunk = c.Kind switch
            {
                "Default" => $"::Valhalla::Detail::defaultConstructThunk<{t.FullEmitName}>",
                "Copy" => $"::Valhalla::Detail::copyConstructThunk<{t.FullEmitName}>",
                "Move" => $"::Valhalla::Detail::moveConstructThunk<{t.FullEmitName}>",
                _ => $"::Valhalla::Detail::customConstructThunk<{string.Join(", ", c.Params.Select(p => p.TypeText).Prepend(t.FullEmitName))}>",
            };
            w.Line($"constexpr ::Valhalla::ConstructorThunkFn kCtor_{t.Ident}_{c.Ident} = &{thunk};");
        }
        w.Line($"constexpr ::Valhalla::DestructorThunkFn kDtor_{t.Ident} = &::Valhalla::Detail::destructThunk<{t.FullEmitName}>;");

        w.Close();
        if (hasNs) w.Close();
        w.Line();
    }

    string ThunkRef(TypeModel t, string name) => $"::{(t.Namespace.Length > 0 ? string.Join("::", t.Namespace) + "::" : "")}{m_ThunkNs}::{name}";

    void EmitParams(CodeWriter w, string arrayName, List<ParamModel> ps, string file, int line)
    {
        if (ps.Count == 0) return;
        w.Open($"constexpr ::Valhalla::ParamDescriptor {arrayName}[] =");
        for (int i = 0; i < ps.Count; i++)
        {
            var p = ps[i];
            WarnCrossModule(p.Type, file, line, $"Parameter '{p.Name}'");
            w.Line($"{{ .m_Name = {Model.Literal(p.Name)}, .m_Type = {TypeRefExpr(p.Type)}, .m_LangTraits = {LangOf(p.Type)}, .m_ReflectTraits = {ReflectOf(p.Type)}, .m_Index = {i} }},");
        }
        w.Close(";");
    }

    void EmitTypeDescriptors(CodeWriter w, TypeModel t)
    {
        string file = t.Source.Header;
        w.Open($"namespace {m_Rtls}");
        w.Line($"static_assert(::Valhalla::fnv1a({Model.Literal(t.QualifiedName)}) == {Hex(t.Hash)}, \"Valhalla-Gen and ValhallaHash.h disagree on FNV-1a\");");

        if (t.Fields.Count > 0)
        {
            w.Open($"constexpr ::Valhalla::FieldDescriptor kFields_{t.Ident}[] =");
            foreach (var f in t.Fields)
            {
                WarnCrossModule(f.Type, file, f.Line, $"Field '{f.Name}'");
                w.Open("");
                w.Line($".m_Name = {Model.Literal(f.Name)},");
                w.Line($".m_DisplayName = {f.Meta.DisplayName},");
                w.Line($".m_Category = {f.Meta.Category},");
                w.Line($".m_Tooltip = {f.Meta.Tooltip},");
                w.Line($".m_Offset = {FieldOffset(t, f)},");
                w.Line($".m_Size = static_cast<uint32_t>(sizeof(decltype({t.FullEmitName}::{f.Name}))),");
                w.Line($".m_Align = {FieldAlign(f, t.FullEmitName)},");
                w.Line($".m_Visibility = ::Valhalla::Visibility::{f.Visibility},");
                w.Line($".m_LangTraits = {Traits("LangTraits", f.LangTraits)},");
                w.Line($".m_ReflectTraits = {Traits("ReflectTraits", f.ReflectTraits)},");
                w.Line($".m_ToolTraits = {Traits("ToolTraits", f.ToolTraits)},");
                w.Line($".m_FieldType = {TypeRefExpr(f.Type)},");
                w.Close(",");
            }
            w.Close(";");
        }

        foreach (var m in t.Methods.Concat(t.Operators))
            EmitParams(w, $"kParams_{t.Ident}_{m.Ident}", m.Params, file, m.Line);
        foreach (var c in t.Constructors)
            EmitParams(w, $"kCtorParams_{t.Ident}_{c.Ident}", c.Params, file, c.Line);

        if (t.Methods.Count > 0)
        {
            w.Open($"constexpr ::Valhalla::MethodDescriptor kMethods_{t.Ident}[] =");
            foreach (var m in t.Methods)
            {
                WarnCrossModule(m.ReturnType, file, m.Line, $"Return type of '{m.Name}'");
                w.Open("");
                w.Line($".m_Name = {Model.Literal(m.Name)},");
                w.Line($".m_DisplayName = {m.Meta.DisplayName},");
                w.Line($".m_Category = {m.Meta.Category},");
                w.Line($".m_Tooltip = {m.Meta.Tooltip},");
                w.Line($".m_Hash = {Hex(Fnv.Hash(m.Name))},");
                w.Line($".m_Visibility = ::Valhalla::Visibility::{m.Visibility},");
                w.Line($".m_LangTraits = {Traits("LangTraits", m.LangTraits)},");
                w.Line($".m_ReflectTraits = {Traits("ReflectTraits", m.ReflectTraits)},");
                w.Line($".m_ToolTraits = {Traits("ToolTraits", m.ToolTraits)},");
                w.Line($".m_ReturnType = {TypeRefExpr(m.ReturnType)},");
                w.Line($".m_Params = {(m.Params.Count > 0 ? $"kParams_{t.Ident}_{m.Ident}" : "nullptr")},");
                w.Line($".m_ParamCount = {m.Params.Count},");
                w.Line($".m_FuncPtr = {(m.ReflectTraits.Contains("Functor") ? $"&{ThunkRef(t, $"kFunctor_{t.Ident}_{m.Ident}")}" : "nullptr")},");
                w.Line($".m_Thunk = {(m.IsAbstract ? "nullptr" : ThunkRef(t, $"kThunk_{t.Ident}_{m.Ident}"))},");
                w.Close(",");
            }
            w.Close(";");
        }

        if (t.Operators.Count > 0)
        {
            w.Open($"constexpr ::Valhalla::OperatorDescriptor kOperators_{t.Ident}[] =");
            foreach (var m in t.Operators)
            {
                WarnCrossModule(m.ReturnType, file, m.Line, $"Return type of '{m.Name}'");
                w.Open("");
                w.Line($".m_Op = ::Valhalla::OperatorKind::{m.Operator},");
                w.Line($".m_Name = {Model.Literal(m.Name)},");
                w.Line($".m_Hash = {Hex(Fnv.Hash(m.Name))},");
                w.Line($".m_Visibility = ::Valhalla::Visibility::{m.Visibility},");
                w.Line($".m_LangTraits = {Traits("LangTraits", m.LangTraits)},");
                w.Line($".m_ReturnType = {TypeRefExpr(m.ReturnType)},");
                w.Line($".m_Params = {(m.Params.Count > 0 ? $"kParams_{t.Ident}_{m.Ident}" : "nullptr")},");
                w.Line($".m_ParamCount = {m.Params.Count},");
                w.Line($".m_Thunk = {(m.IsAbstract ? "nullptr" : ThunkRef(t, $"kThunk_{t.Ident}_{m.Ident}"))},");
                w.Close(",");
            }
            w.Close(";");
        }

        if (t.Constructors.Count > 0)
        {
            w.Open($"constexpr ::Valhalla::ConstructorDescriptor kConstructors_{t.Ident}[] =");
            foreach (var c in t.Constructors)
            {
                int count = c.Kind switch { "Default" => 0, "Copy" or "Move" => 1, _ => c.Params.Count };
                string ps = c.Params.Count > 0 ? $"kCtorParams_{t.Ident}_{c.Ident}" : "nullptr";
                w.Line($"{{ .m_Visibility = ::Valhalla::Visibility::{c.Visibility}, .m_Kind = ::Valhalla::ConstructorKind::{c.Kind}, .m_Params = {ps}, .m_ParamCount = {count}, .m_Thunk = {ThunkRef(t, $"kCtor_{t.Ident}_{c.Ident}")} }},");
            }
            w.Close(";");
        }

        string align = t.Align is int a ? $"{a}u" : $"static_cast<uint32_t>(alignof({t.FullEmitName}))";
        string parent = "nullptr";
        if (t.Parent != null)
        {
            if (m_Inv.OwnerOf(t.Parent) == m_Module) parent = $"&kType_{t.Parent.Ident}";
            else Diag.Warning(file, t.Source.Line, $"Parent '{t.Parent.QualifiedName}' is in another module; m_Parent is left null (CTLS kParentHash still identifies it).");
        }

        w.Open($"const ::Valhalla::TypeDescriptor kType_{t.Ident} =");
        w.Line($".m_Name = {Model.Literal(t.QualifiedName)},");
        w.Line($".m_DisplayName = {t.Meta.DisplayName},");
        w.Line($".m_Category = {t.Meta.Category},");
        w.Line($".m_Tooltip = {t.Meta.Tooltip},");
        w.Line($".m_Hash = {Hex(t.Hash)},");
        w.Line($".m_ObjectType = ::Valhalla::ObjectType::{(t.IsClass ? "Class" : "Struct")},");
        w.Line($".m_Size = static_cast<uint32_t>(sizeof({t.FullEmitName})),");
        w.Line($".m_Align = {align},");
        w.Line($".m_Parent = {parent},");
        w.Line($".m_Fields = {(t.Fields.Count > 0 ? $"kFields_{t.Ident}" : "nullptr")},");
        w.Line($".m_FieldCount = {t.Fields.Count},");
        w.Line($".m_Methods = {(t.Methods.Count > 0 ? $"kMethods_{t.Ident}" : "nullptr")},");
        w.Line($".m_MethodCount = {t.Methods.Count},");
        w.Line($".m_Operators = {(t.Operators.Count > 0 ? $"kOperators_{t.Ident}" : "nullptr")},");
        w.Line($".m_OperatorCount = {t.Operators.Count},");
        w.Line($".m_Constructors = {(t.Constructors.Count > 0 ? $"kConstructors_{t.Ident}" : "nullptr")},");
        w.Line($".m_ConstructorCount = {t.Constructors.Count},");
        w.Line(".m_EnumValues = nullptr,");
        w.Line(".m_EnumValueCount = 0,");
        w.Line($".m_Destructor = {ThunkRef(t, $"kDtor_{t.Ident}")},");
        w.Close(";");
        w.Close();
        w.Line();
    }

    void EmitEnumDescriptor(CodeWriter w, EnumModel e)
    {
        w.Open($"namespace {m_Rtls}");
        w.Line($"static_assert(::Valhalla::fnv1a({Model.Literal(e.QualifiedName)}) == {Hex(e.Hash)}, \"Valhalla-Gen and ValhallaHash.h disagree on FNV-1a\");");
        if (e.Values.Count > 0)
        {
            w.Open($"constexpr ::Valhalla::EnumValueDescriptor kEnumValues_{e.Ident}[] =");
            foreach (var v in e.Values)
            {
                string value = v.Override is long o ? $"{o}LL" : $"static_cast<int64_t>({e.FullEmitName}::{v.Name})";
                w.Line($"{{ .m_Name = {Model.Literal(v.Name)}, .m_DisplayName = {v.DisplayName}, .m_Value = {value} }},");
            }
            w.Close(";");
        }
        w.Open($"const ::Valhalla::TypeDescriptor kType_{e.Ident} =");
        w.Line($".m_Name = {Model.Literal(e.QualifiedName)},");
        w.Line($".m_DisplayName = {e.Meta.DisplayName},");
        w.Line($".m_Category = {e.Meta.Category},");
        w.Line($".m_Tooltip = {e.Meta.Tooltip},");
        w.Line($".m_Hash = {Hex(e.Hash)},");
        w.Line(".m_ObjectType = ::Valhalla::ObjectType::Enum,");
        w.Line($".m_Size = static_cast<uint32_t>(sizeof({e.FullEmitName})),");
        w.Line($".m_Align = static_cast<uint32_t>(alignof({e.FullEmitName})),");
        w.Line(".m_Parent = nullptr,");
        w.Line(".m_Fields = nullptr,");
        w.Line(".m_FieldCount = 0,");
        w.Line(".m_Methods = nullptr,");
        w.Line(".m_MethodCount = 0,");
        w.Line(".m_Operators = nullptr,");
        w.Line(".m_OperatorCount = 0,");
        w.Line(".m_Constructors = nullptr,");
        w.Line(".m_ConstructorCount = 0,");
        w.Line($".m_EnumValues = {(e.Values.Count > 0 ? $"kEnumValues_{e.Ident}" : "nullptr")},");
        w.Line($".m_EnumValueCount = {e.Values.Count},");
        w.Line(".m_Destructor = nullptr,");
        w.Close(";");
        w.Close();
        w.Line();
    }

    void EmitModuleRegistry(CodeWriter w)
    {
        var entries = m_Types.Select(t => (Hash: t.Hash, Ident: t.Ident, Name: t.QualifiedName, File: t.Source.Header, Line: t.Source.Line))
            .Concat(m_Enums.Select(e => (Hash: e.Hash, Ident: e.Ident, Name: e.QualifiedName, File: e.Source.Header, Line: e.Source.Line)))
            .ToList();

        foreach (var dup in entries.GroupBy(e => e.Hash).Where(g => g.Count() > 1))
            Diag.Error(dup.First().File, dup.First().Line, $"FNV-1a collision between {string.Join(", ", dup.Select(d => d.Name))}; rename one.");
        foreach (var dup in entries.GroupBy(e => e.Ident).Where(g => g.Count() > 1))
            Diag.Error(dup.First().File, dup.First().Line, $"{string.Join(", ", dup.Select(d => d.Name))} map to the same generated identifier; rename one.");
        if (Diag.ErrorCount > 0) return;

        var chd = ChdTable.Build(entries.Select(e => e.Hash).ToList());

        w.Open($"namespace {m_Rtls}");
        if (entries.Count > 0)
        {
            w.Line($"constexpr uint32_t kChdDisplacements[] = {{ {string.Join(", ", chd.Displacements.Select(d => d + "u"))} }};");
            w.Open("constexpr const ::Valhalla::TypeDescriptor* kChdSlots[] =");
            foreach (uint key in chd.SlotToKey)
                w.Line(key == ChdTable.EmptySlot ? "nullptr," : $"&kType_{entries[(int)key].Ident},");
            w.Close(";");
            for (uint slot = 0; slot < chd.SlotCount; slot++)
            {
                uint key = chd.SlotToKey[slot];
                if (key == ChdTable.EmptySlot) continue;
                string h = Hex(entries[(int)key].Hash);
                w.Line($"static_assert(::Valhalla::Chd::slotOf({h}, kChdDisplacements[::Valhalla::Chd::bucketOf({h}, {chd.BucketCount}u)], {chd.SlotCount}u) == {slot}u, \"Valhalla-Gen and ValhallaChd.h disagree on CHD lookup\");");
            }
            w.Line();
        }
        w.Open("const ::Valhalla::ModuleRegistry kModule =");
        w.Line($".m_Name = {Model.Literal(m_Module.ModuleName)},");
        w.Line($".m_DllHash = {Hex(m_Module.DllHash)},");
        w.Line($".m_BucketCount = {chd.BucketCount}u,");
        w.Line($".m_SlotCount = {chd.SlotCount}u,");
        w.Line($".m_Displacements = {(entries.Count > 0 ? "kChdDisplacements" : "nullptr")},");
        w.Line($".m_Slots = {(entries.Count > 0 ? "kChdSlots" : "nullptr")},");
        w.Line($".m_TypeCount = {entries.Count}u,");
        w.Close(";");
        w.Line($"static_assert(::Valhalla::fnv1a({Model.Literal(m_Module.DllIdentity)}) == {Hex(m_Module.DllHash)}, \"Valhalla-Gen and ValhallaHash.h disagree on FNV-1a\");");
        w.Close();
        w.Line();

        w.Open($"namespace {m_Module.Namespace}");
        w.Open("void RegisterAll(::Valhalla::RegistrationHook p_Hook)");
        w.Line($"::Valhalla::RegisterModule(&::{m_Rtls}::kModule, p_Hook);");
        w.Close();
        w.Close();
        w.Line();
        w.Open("namespace");
        w.Line($"const ::Valhalla::AutoRegistration s_ValhallaRegistration(&::{m_Module.Namespace}::RegisterAll);");
        w.Close();
    }
}
