cmake_minimum_required(VERSION 3.20)
project(ValhallaCore LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

file(GLOB_RECURSE ValhallaCore_HEADERS  CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/Public/*.h")
file(GLOB_RECURSE ValhallaCore_SOURCE   CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/Private/*.cpp")
file(GLOB_RECURSE ValhallaCore_INL      CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/src/Public/*.inl")

add_library(ValhallaCore SHARED
    ${ValhallaCore_HEADERS}
    ${ValhallaCore_SOURCE}
    ${ValhallaCore_INL}
)
target_compile_definitions(ValhallaCore PRIVATE ValhallaCore_EXPORTS)
target_include_directories(ValhallaCore PUBLIC
    ${CMAKE_CURRENT_SOURCE_DIR}/src/Public
)

target_precompile_headers(ValhallaCore PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/src/Public/ValhallaCore.h)

target_compile_options(ValhallaCore PRIVATE
    $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_ID:MSVC>>:/arch:AVX2 /W4 /permissive->
    $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<NOT:$<CXX_COMPILER_ID:MSVC>>>:-mavx2 -Wall -Wextra>
)
